### ISSUE TITLE
Can't access share on my NAS anonymously

### ISSUE THREAD

**Issue by lsahnicne** [cy33hc/ps4-smb-client#2]
I have an SMB share on my NAS running OpenMediaVault. It is configured to be accessible with read permissions by anybody:

> [global]
> ...
> guest account = nobody
> map to guest = Bad User
> ...
> 
> [share1]
> path = /...
> guest ok = yes
> guest only = no
> read only = yes
> browseable = yes
> inherit acls = yes
> inherit permissions = yes
> ea support = no
> store dos attributes = no
> vfs objects =
> printable = no
> create mask = 0664
> force create mode = 0664
> directory mask = 0775
> force directory mode = 0775
> hide special files = yes
> follow symlinks = yes
> hide dot files = yes
> read list =
> write list = @users

When i try to access it from PS4 without entering login and password, the following error message appears:
> 426 Failed. Connection timeout. - Tree Connect failed with (0xc0000022) STATUS_ACCESS_DENIED

**Comment by cy33hc** [comment]
@lsahnicne Hi. I made some changes that should fix anonymous login. Can you try the latest release 1.06.

**Comment by lsahnicne** [comment]
Yes, I'm able connect without entering login & password using 1.06
