### ISSUE TITLE
Downloading is unavailable

### ISSUE THREAD

**Issue by lsahnicne** [cy33hc/ps4-smb-client#4]
After connecting to share, the 'Download' option is greyed out and cannot be selected. User has full write/read permissions. PS4 has enough free space.

![PS4 SMB Client_20230103114642_](https://user-images.githubusercontent.com/43319094/210328294-63c7b87b-76de-46ea-a2ca-2c3ca92498d4.jpg)

**Comment by cy33hc** [comment]
@lsahnicne You need to highlight the files to download with the "Square" button.

**Comment by lsahnicne** [comment]
That's rather unintuitive. All the interfaces i've ever used apply context menu to the item selection cursor is currently on.

**Comment by cy33hc** [comment]
@lsahnicne if you consider multi-select, then it's intuitive.
